# Generated by Django 4.0.3 on 2023-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='vin',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
