# Generated by Django 4.0.3 on 2023-04-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ('id',), 'verbose_name_plural': 'statuses'},
        ),
    ]
