# Generated by Django 4.0.3 on 2023-04-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Technician',
        ),
        migrations.AddField(
            model_name='appointment',
            name='technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technician', to='service_rest.technician'),
        ),
    ]
